FROM ispcp-waf-test
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openssh-server openssh-client python3 sudo default-mysql-client git util-linux && rm -rf /var/lib/apt/lists/*
